<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AssemblyName>BlazorFlowGraph.Blazor</AssemblyName>
    <RootNamespace>BlazorFlowGraph.Blazor</RootNamespace>
    <Description>Razor components for the dataflow visualizer.</Description>
    <AddRazorSupportForMvc>false</AddRazorSupportForMvc>
    <IsPackable>true</IsPackable>
    <PackageId>BlazorFlowGraph.Blazor</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <ProjectReference Include="../BlazorFlowGraph.Protocol/BlazorFlowGraph.Protocol.csproj" />
    <ProjectReference Include="../BlazorFlowGraph.Diffing/BlazorFlowGraph.Diffing.csproj" />
  </ItemGroup>

</Project>
