<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AssemblyName>Diagram.Blazor</AssemblyName>
    <RootNamespace>Diagram.Blazor</RootNamespace>
    <Description>Razor components for the dataflow visualizer.</Description>
    <AddRazorSupportForMvc>false</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <ProjectReference Include="../Diagram.Protocol/Diagram.Protocol.csproj" />
    <ProjectReference Include="../Diagram.Diffing/Diagram.Diffing.csproj" />
  </ItemGroup>

</Project>
